name: 💡 Feature idea
description: Idea or request
title: "💡 "
labels: ["💡 Feature idea"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🌟 **Thank you for contributing!**

  - type: textarea
    id: what
    attributes:
      label: What?
      description: What is this feature?
      placeholder: |
        For example describe a new API endpoint, a change in wording,
        a new configuration option, ...
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why?
      description: Why do we need or want this feature?
      placeholder: |
        Give context and describe the problem the idea solves
    validations:
      required: true

  - type: textarea
    id: how
    attributes:
      label: How?
      description: How can we realize this feature?
      placeholder: |
        Which technical solutions, libraries or systems should be used, which
        components need to change, steps how to implement this, ...
    validations:
      required: true